name: Generate SDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout the server repository
        uses: actions/checkout@v2
        with:
          repository: carthage-software/server
          path: server

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: composer install

      - name: Install OpenAPI CLI
        run: npm install -g @redocly/openapi-cli

      - name: Bundle the OpenAPI Specification
        run: openapi bundle spec/Specification.yaml --ext json -o open-api.json
        working-directory: server

      - name: Generate SDK
        run: |
          ls -la
          ls -la server
          php vendor/bin/jane-openapi generate --config-file=jane.php
          php vendor/bin/php-cs-fixer fix

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: re-generate the software development kit'
          branch: main
          commit_user_name: azjezz
          commit_user_email: azjezz@protonmail.com
          commit_author: azjezz <azjezz@protonmail.com>
          file_pattern: 'src/*'
